### ISSUE TITLE
purrr 1.0.0 and `modify.forest`

### ISSUE THREAD

**Issue by hadley** [UchidaMizuki/timbr#1]
This is just a note to let you know that we've decided to turn `purrr::modify()` back into a regular function so it will no longer be an S3 generic. You're the only package that provided a method, and I think you can just change `modify.forest` into it's own `modify_forest` function.

**Comment by UchidaMizuki** [comment]
I have fixed this problem and updated the version of the package.

**Comment by hadley** [comment]
Thank you!
